### YouTube Transcript API Tests
### REST Client for VS Code

@baseUrl = http://localhost:3001
@youtubeUrl = https://www.youtube.com/watch?v=cxSowU9sDdU&ab_channel=KevinPowell

### Health Check
GET {{baseUrl}}/health
Content-Type: application/json

### Take Screenshot
GET {{baseUrl}}/api/screenshot?url={{youtubeUrl}}
Content-Type: application/json


###

### Get Transcript
GET {{baseUrl}}/api/transcript?url={{youtubeUrl}}
Content-Type: application/json


